#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <arpa/inet.h>
#include <ctype.h>
#include <sys/stat.h>
#include <dirent.h>

#include "pages.h"


void send_page_1(int client_socket) {
    const char *html =
        "HTTP/1.1 200 OK\r\n"
        "Content-Type: text/html\r\n"
        "\r\n"
        "<!DOCTYPE html>"
        "<html lang='en'>"
        "<head>"
        "<meta charset='UTF-8'>"
        "<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
        "<title>Page 1</title>"
        "<style>"
        "body {"
        "    font-family: Arial, sans-serif;"
        "    background: linear-gradient(135deg, #2c3e50, #34495e);"
	"    color: #333;"
        "    margin: 0;"
        "    padding: 0;"
        "    display: flex;"
        "    justify-content: center;"
        "    align-items: center;"
        "    height: 100vh;"
        "}"
        ".container {"
        "    background: #ffffff;"
        "    padding: 20px;"
        "    border-radius: 10px;"
        "    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);"
        "    text-align: center;"
        "    width: 90%;"
        "    max-width: 400px;"
        "}"
        "h1 {"
        "    color: #4CAF50;"
        "    margin-bottom: 20px;"
        "}"
        "form {"
        "    display: flex;"
        "    flex-direction: column;"
        "    align-items: center;"
        "}"
        "input[type='text'] {"
        "    padding: 10px;"
        "    width: 100%;"
        "    margin-bottom: 20px;"
        "    border: 1px solid #ccc;"
        "    border-radius: 5px;"
        "    font-size: 16px;"
        "}"
        "button {"
        "    background-color: #4CAF50;"
        "    color: white;"
        "    border: none;"
        "    padding: 10px 20px;"
        "    border-radius: 5px;"
        "    cursor: pointer;"
        "    font-size: 16px;"
        "}"
        "button:hover {"
        "    background-color: #45a049;"
        "}"
        "</style>"
        "</head>"
        "<body>"
        "<div class='container'>"
        "    <h1>Welcome</h1>"
        "    <p>Please enter your name to proceed:</p>"
        "    <form method='POST' action='/'>"
        "        <input type='text' name='name' placeholder='Enter your name' required>"
        "        <button type='submit'>Next</button>"
        "    </form>"
        "</div>"
        "</body>"
        "</html>";
    write(client_socket, html, strlen(html));
}



void send_page_2(int client_socket,const char *message) {
        char html[BUFF_SIZE];
    	snprintf(html, sizeof(html),
        "HTTP/1.1 200 OK\r\n"
        "Content-Type: text/html\r\n"
        "\r\n"
        "<!DOCTYPE html>"
        "<html>"
        "<head>"
        "<title>Page 2</title>"
        "<style>"
        "body {"
        "    margin: 0;"
        "    font-family: Arial, sans-serif;"
        "    background: linear-gradient(135deg, #2c3e50, #34495e);"
        "    color: #ecf0f1;"
        "    display: flex;"
        "    justify-content: center;"
        "    align-items: center;"
        "    height: 100vh;"
        "}"
        "h1 {"
        "    text-align: center;"
        "}"
        "form {"
        "    background: #1c2833;"
        "    padding: 20px;"
        "    border-radius: 8px;"
        "    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3);"
        "    text-align: center;"
        "}"
        "input[type='text'] {"
        "    padding: 10px;"
        "    margin: 10px 0;"
	"    width: calc(100%% - 24px);"

        "    border: none;"
        "    border-radius: 4px;"
        "    font-size: 16px;"
        "}"
        "button {"
        "    padding: 10px 20px;"
        "    border: none;"
        "    border-radius: 4px;"
        "    background: #3498db;"
        "    color: white;"
        "    font-size: 16px;"
        "    cursor: pointer;"
        "}"
        "button:hover {"
        "    background: #2980b9;"
        "}"
        "</style>"
        "</head>"
        "<body>"
        "<form method='POST' action='/send'>"
	"<h1>Welcome %s</h1>"
        "<h1>Enter Your Path</h1>"
        "<input type='text' name='message' placeholder='Enter the file or directory path' required>"
        "<button type='submit'>Send</button>"
        "</form>"
        "</body>"
        "</html>",message);
    write(client_socket, html, strlen(html));
}



void send_page_3(int client_socket, const char *message) {
    char html[BUFF_SIZE];
    snprintf(html, sizeof(html),
        "HTTP/1.1 200 OK\r\n"
        "Content-Type: text/html\r\n"
        "\r\n"
        "<!DOCTYPE html>"
        "<html>"
        "<head>"
        "<title>Page 3</title>"
        "<style>"
        "body {"
        "    margin: 0;"
        "    font-family: Arial, sans-serif;"
        "    background: linear-gradient(135deg, #2c3e50, #34495e);"
        "    color: #ecf0f1;"
        "    display: flex;"
        "    flex-direction: column;"
        "    justify-content: center;"
        "    align-items: center;"
        "    height: 100vh;"
        "}"
        "h1 {"
        "    margin-bottom: 20px;"
        "}"
        "p {"
        "    background: #1c2833;"
        "    padding: 15px;"
        "    border-radius: 8px;"
        "    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3);"
        "    font-size: 18px;"
        "    text-align: center;"
        "    width: 80%%;" // Escaped '%' as '%%'
        "    max-width: 600px;"
        "}"
        "form {"
        "    margin-top: 10px;"
        "}"
        "button {"
        "    padding: 10px 20px;"
        "    border: none;"
        "    border-radius: 4px;"
        "    background: #3498db;"
        "    color: white;"
        "    font-size: 16px;"
        "    cursor: pointer;"
        "    margin: 5px;"
        "}"
        "button:hover {"
        "    background: #2980b9;"
        "}"
        "</style>"
        "</head>"
        "<body>"
        "<h1>Server Response</h1>"
        "<p>%s</p>"
        "<form method='POST' action='/back'>"
        "<button type='submit'>Go Back</button>"
        "</form>"
        "<form method='POST' action='/end'>"
        "<button type='submit'>End</button>"
        "</form>"
        "</body>"
        "</html>", message);
    write(client_socket, html, strlen(html));
}
